import React, { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { FolderOpen, Plus, Search, RefreshCw, Pencil, Trash2, X, ImagePlus, Tags, CheckCircle2 } from "lucide-react";
import { toast } from "sonner";

const API = "http://localhost:3000/api";
const getArray = (r, key) => [r?.data?.data?.[key], r?.data?.[key], r?.data?.data, r?.data].find(Array.isArray) || [];
const messageOf = (e) => e.response?.data?.message || e.response?.data?.error || e.message || "Request failed";
const AdminCategories = ({ theme = "dark" }) => {
  const dark = theme === "dark";
  const [categories, setCategories] = useState([]), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false);
  const [search, setSearch] = useState(""), [modal, setModal] = useState(false), [editing, setEditing] = useState(null), [remove, setRemove] = useState(null), [file, setFile] = useState(null);
  const blank = { name: "", description: "", isActive: true };
  const [form, setForm] = useState(blank);
  const config = useCallback((multipart = false) => { const token = localStorage.getItem("accessToken"); return { withCredentials: true, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(multipart ? { "Content-Type": "multipart/form-data" } : {}) } }; }, []);
  const load = useCallback(async () => { setLoading(true); try { const r = await axios.get(`${API}/categories/all`, config()); setCategories(getArray(r, "categories")); } catch (e) { toast.error(messageOf(e)); } finally { setLoading(false); } }, [config]);
  useEffect(() => { load(); }, [load]);
  const filtered = useMemo(() => categories.filter(c => `${c.name || ""} ${c.description || ""}`.toLowerCase().includes(search.toLowerCase())), [categories, search]);
  const open = (category = null) => { setEditing(category); setForm(category ? { name: category.name || "", description: category.description || "", isActive: category.isActive !== false } : blank); setFile(null); setModal(true); };
  const save = async (e) => { e.preventDefault(); if (!form.name.trim()) return toast.error("Category name is required"); setBusy(true); try { const data = new FormData(); data.append("name", form.name.trim()); data.append("description", form.description); data.append("isActive", String(form.isActive)); if (file) data.append("CategoryImage", file); const id = editing?._id || editing?.id; if (editing) await axios.put(`${API}/categories/${id}`, data, config(true)); else await axios.post(`${API}/categories`, data, config(true)); toast.success(editing ? "Category updated" : "Category created"); setModal(false); await load(); } catch (e) { toast.error(messageOf(e)); } finally { setBusy(false); } };
  const deleteCategory = async () => { if (!remove) return; setBusy(true); try { await axios.delete(`${API}/categories/${remove._id || remove.id}`, config()); toast.success("Category deleted"); setRemove(null); await load(); } catch (e) { toast.error(messageOf(e)); } finally { setBusy(false); } };
  const panel = dark ? "border-white/10 bg-slate-900/70" : "border-slate-200 bg-white"; const text = dark ? "text-slate-100" : "text-slate-800"; const muted = dark ? "text-slate-400" : "text-slate-500"; const field = `w-full rounded-xl border px-3 py-2.5 text-sm outline-none focus:border-violet-500 ${dark ? "border-white/10 bg-slate-950 text-slate-100" : "border-slate-200 bg-white text-slate-800"}`;
  return <section className={`min-h-[65vh] ${text}`}>
    <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.2em] text-violet-500">Store management</p><h1 className="text-2xl font-bold sm:text-3xl">Categories</h1><p className={`mt-1 text-sm ${muted}`}>Create and maintain your product categories.</p></div><div className="flex gap-2"><button onClick={load} className={`flex items-center gap-2 rounded-xl border px-3 py-2.5 text-sm ${panel}`}><RefreshCw size={15}/> Refresh</button><button onClick={() => open()} className="flex items-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-violet-500"><Plus size={16}/> Add category</button></div></div>
    <div className={`mb-5 grid gap-4 sm:grid-cols-3`}><div className={`rounded-2xl border p-5 ${panel}`}><Tags className="mb-3 text-violet-500"/><p className={`text-sm ${muted}`}>Total categories</p><p className="mt-1 text-2xl font-bold">{categories.length}</p></div><div className={`rounded-2xl border p-5 ${panel}`}><CheckCircle2 className="mb-3 text-emerald-500"/><p className={`text-sm ${muted}`}>Active</p><p className="mt-1 text-2xl font-bold">{categories.filter(c => c.isActive !== false).length}</p></div><div className={`rounded-2xl border p-5 ${panel}`}><FolderOpen className="mb-3 text-amber-500"/><p className={`text-sm ${muted}`}>Inactive</p><p className="mt-1 text-2xl font-bold">{categories.filter(c => c.isActive === false).length}</p></div></div>
    <div className={`overflow-hidden rounded-2xl border ${panel}`}><div className="border-b border-inherit p-4"><div className="relative max-w-md"><Search size={16} className={`absolute left-3 top-1/2 -translate-y-1/2 ${muted}`}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search categories..." className={`${field} pl-9`}/></div></div>
      {loading ? <div className={`p-12 text-center ${muted}`}>Loading categories…</div> : filtered.length === 0 ? <div className={`p-12 text-center ${muted}`}>No categories found. Add your first category.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className={dark ? "bg-white/[.04] text-slate-400" : "bg-slate-50 text-slate-500"}><tr>{["Category", "Description", "Status", "Actions"].map(x => <th key={x} className="px-5 py-4 text-xs font-semibold uppercase tracking-wide">{x}</th>)}</tr></thead><tbody>{filtered.map(c => <tr key={c._id || c.id} className="border-t border-inherit"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-xl bg-violet-500/10 text-violet-500">{(c.CategoryImage?.secure_url || c.CategoryImage?.url || c.CategoryImage || c.image) ? <img className="h-full w-full object-cover" src={typeof (c.CategoryImage || c.image) === "string" ? (c.CategoryImage || c.image) : (c.CategoryImage?.secure_url || c.CategoryImage?.url)} alt=""/> : <FolderOpen size={18}/>}</div><span className="font-semibold">{c.name || "Unnamed category"}</span></div></td><td className={`max-w-xs truncate px-5 py-4 ${muted}`}>{c.description || "—"}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${c.isActive === false ? "bg-rose-500/10 text-rose-500" : "bg-emerald-500/10 text-emerald-500"}`}>{c.isActive === false ? "Inactive" : "Active"}</span></td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={() => open(c)} className="rounded-lg border border-inherit p-2 hover:text-violet-500" title="Edit"><Pencil size={15}/></button><button onClick={() => setRemove(c)} className="rounded-lg border border-inherit p-2 hover:text-rose-500" title="Delete"><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>}</div>
    {modal && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4"><form onSubmit={save} className={`w-full max-w-lg rounded-2xl border p-6 shadow-2xl ${panel}`}><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">{editing ? "Edit category" : "Create category"}</h2><button type="button" onClick={() => setModal(false)}><X size={18}/></button></div><label className="mb-1 block text-sm font-medium">Name *</label><input className={`${field} mb-4`} value={form.name} onChange={e => setForm({...form, name:e.target.value})} required/><label className="mb-1 block text-sm font-medium">Description</label><textarea rows={3} className={`${field} mb-4`} value={form.description} onChange={e => setForm({...form, description:e.target.value})}/><label className="mb-1 block text-sm font-medium">Category image</label><label className={`mb-4 flex cursor-pointer items-center gap-2 rounded-xl border border-dashed border-inherit p-3 text-sm ${muted}`}><ImagePlus size={18}/> {file?.name || "Choose image (optional)"}<input type="file" accept="image/*" className="hidden" onChange={e => setFile(e.target.files?.[0] || null)}/></label><label className="mb-5 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isActive} onChange={e => setForm({...form,isActive:e.target.checked})}/> Active category</label><div className="flex justify-end gap-2"><button type="button" onClick={() => setModal(false)} className={`rounded-xl border border-inherit px-4 py-2 text-sm`}>Cancel</button><button disabled={busy} className="rounded-xl bg-violet-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Saving…" : editing ? "Save changes" : "Create category"}</button></div></form></div>}
    {remove && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4"><div className={`w-full max-w-sm rounded-2xl border p-6 ${panel}`}><h3 className="text-lg font-bold">Delete category?</h3><p className={`my-3 text-sm ${muted}`}>Delete “{remove.name}”? Products assigned to it may be affected depending on your backend.</p><div className="flex justify-end gap-2"><button onClick={() => setRemove(null)} className="rounded-xl border border-inherit px-4 py-2 text-sm">Cancel</button><button disabled={busy} onClick={deleteCategory} className="rounded-xl bg-rose-600 px-4 py-2 text-sm font-semibold text-white">{busy ? "Deleting…" : "Delete"}</button></div></div></div>}
  </section>;
};
export default AdminCategories;
