import React, { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { Users, Search, RefreshCw, ShieldCheck, UserRound, Mail, X } from "lucide-react";
import { toast } from "sonner";
const API = "http://localhost:3000/api";
const getArray = (r, key) => [r?.data?.data?.[key], r?.data?.[key], r?.data?.data, r?.data].find(Array.isArray) || [];
const errMsg = e => e.response?.data?.message || e.response?.data?.error || e.message || "Request failed";
const AdminUser = ({ theme = "dark" }) => {
  const dark = theme === "dark"; const [users,setUsers] = useState([]), [loading,setLoading] = useState(true), [search,setSearch] = useState(""), [role,setRole] = useState("all"), [selected,setSelected] = useState(null);
  const config = useCallback(() => { const token=localStorage.getItem("accessToken"); return {withCredentials:true,headers:token?{Authorization:`Bearer ${token}`}:{}}; },[]);
  const load = useCallback(async () => { setLoading(true); try { const r=await axios.get(`${API}/auth/all-user`,config()); if(r.data?.statusText === "error") throw new Error(r.data?.message || "Could not load users"); setUsers(getArray(r,"users")); } catch(e) { toast.error(errMsg(e)); } finally {setLoading(false);} },[config]);
  useEffect(()=>{load();},[load]);
  const filtered=useMemo(()=>users.filter(u=>`${u.firstName||""} ${u.lastName||""} ${u.name||""} ${u.email||""}`.toLowerCase().includes(search.toLowerCase()) && (role==="all" || String(u.role||"user").toLowerCase()===role)),[users,search,role]);
  const panel=dark?"border-white/10 bg-slate-900/70":"border-slate-200 bg-white", text=dark?"text-slate-100":"text-slate-800", muted=dark?"text-slate-400":"text-slate-500", field=`rounded-xl border px-3 py-2.5 text-sm outline-none focus:border-violet-500 ${dark?"border-white/10 bg-slate-950 text-slate-100":"border-slate-200 bg-white text-slate-800"}`;
  const displayName=u=>[u.firstName,u.lastName].filter(Boolean).join(" ")||u.name||"Unnamed user";
  return <section className={`min-h-[65vh] ${text}`}><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.2em] text-violet-500">Store management</p><h1 className="text-2xl font-bold sm:text-3xl">Users</h1><p className={`mt-1 text-sm ${muted}`}>Review registered accounts and account roles.</p></div><button onClick={load} className={`flex items-center justify-center gap-2 rounded-xl border px-3 py-2.5 text-sm ${panel}`}><RefreshCw size={15}/> Refresh users</button></div>
    <div className="mb-5 grid gap-4 sm:grid-cols-3"><div className={`rounded-2xl border p-5 ${panel}`}><Users className="mb-3 text-violet-500"/><p className={`text-sm ${muted}`}>Total users</p><p className="mt-1 text-2xl font-bold">{users.length}</p></div><div className={`rounded-2xl border p-5 ${panel}`}><UserRound className="mb-3 text-sky-500"/><p className={`text-sm ${muted}`}>Customers</p><p className="mt-1 text-2xl font-bold">{users.filter(u=>String(u.role||"user").toLowerCase()!=="admin").length}</p></div><div className={`rounded-2xl border p-5 ${panel}`}><ShieldCheck className="mb-3 text-emerald-500"/><p className={`text-sm ${muted}`}>Admins</p><p className="mt-1 text-2xl font-bold">{users.filter(u=>String(u.role).toLowerCase()==="admin").length}</p></div></div>
    <div className={`overflow-hidden rounded-2xl border ${panel}`}><div className="flex flex-col gap-3 border-b border-inherit p-4 sm:flex-row"><div className="relative flex-1"><Search size={16} className={`absolute left-3 top-1/2 -translate-y-1/2 ${muted}`}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or email…" className={`${field} w-full pl-9`}/></div><select value={role} onChange={e=>setRole(e.target.value)} className={field}><option value="all">All roles</option><option value="user">Customers</option><option value="admin">Admins</option></select></div>
    {loading?<div className={`p-12 text-center ${muted}`}>Loading users…</div>:filtered.length===0?<div className={`p-12 text-center ${muted}`}>No users found.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className={dark?"bg-white/[.04] text-slate-400":"bg-slate-50 text-slate-500"}><tr>{["User","Email","Role","Verification","Details"].map(x=><th key={x} className="px-5 py-4 text-xs font-semibold uppercase tracking-wide">{x}</th>)}</tr></thead><tbody>{filtered.map(u=><tr key={u._id||u.id||u.email} className="border-t border-inherit"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-full bg-violet-500/10 font-bold text-violet-500">{displayName(u).slice(0,1).toUpperCase()}</div><div><p className="font-semibold">{displayName(u)}</p><p className={`text-xs ${muted}`}>ID: {String(u._id||u.id||"—").slice(-8)}</p></div></div></td><td className={`px-5 py-4 ${muted}`}><span className="inline-flex items-center gap-2"><Mail size={14}/>{u.email||"—"}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${String(u.role).toLowerCase()==="admin"?"bg-violet-500/10 text-violet-500":"bg-sky-500/10 text-sky-500"}`}>{u.role||"user"}</span></td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${(u.isVerified===true||u.isVerified===undefined)?"bg-emerald-500/10 text-emerald-500":"bg-amber-500/10 text-amber-500"}`}>{u.isVerified===true?"Verified":u.isVerified===false?"Unverified":"Unknown"}</span></td><td className="px-5 py-4"><button onClick={()=>setSelected(u)} className="rounded-lg border border-inherit px-3 py-2 text-xs font-semibold hover:text-violet-500">View details</button></td></tr>)}</tbody></table></div>}</div>
    {selected&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4"><div className={`w-full max-w-md rounded-2xl border p-6 ${panel}`}><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">User details</h2><button onClick={()=>setSelected(null)}><X size={18}/></button></div><div className="space-y-3 text-sm">{[["Name",displayName(selected)],["Email",selected.email||"—"],["Role",selected.role||"user"],["Verified",selected.isVerified===true?"Yes":selected.isVerified===false?"No":"Unknown"],["User ID",selected._id||selected.id||"—"]].map(([k,v])=><div key={k} className="flex justify-between gap-4 border-b border-inherit pb-3"><span className={muted}>{k}</span><span className="max-w-[65%] break-all text-right font-medium">{String(v)}</span></div>)}</div><p className={`mt-4 text-xs ${muted}`}>This screen is read-only. User role changes are intentionally not enabled.</p></div></div>}
  </section>;
}; export default AdminUser;
