import React, { useCallback, useEffect, useMemo, useState } from "react";
import axios from "axios";
import { BellRing, RefreshCw, Search, ShoppingBag, Clock3, CheckCircle2, Truck, XCircle, Eye, X } from "lucide-react";
import { toast } from "sonner";
const API = "http://localhost:3000/api";
const getArray = (r, key) => [r?.data?.data?.[key], r?.data?.[key], r?.data?.data, r?.data].find(Array.isArray) || [];
const errMsg = e => e.response?.data?.message || e.response?.data?.error || e.message || "Request failed";
const money = n => new Intl.NumberFormat("en-PK", { style: "currency", currency: "PKR", maximumFractionDigits: 0 }).format(Number(n) || 0);
const orderId = o => o._id || o.id || o.orderId || "—";
const orderStatus = o => o.orderStatus || o.status || "Pending";
const AdminOrderNotification = ({ theme = "dark" }) => {
    const dark = theme === "dark"; const [orders, setOrders] = useState([]), [loading, setLoading] = useState(true), [search, setSearch] = useState(""), [status, setStatus] = useState("all"), [selected, setSelected] = useState(null), [updating, setUpdating] = useState("");
    const config = useCallback(() => { const token = localStorage.getItem("accessToken"); return { withCredentials: true, headers: token ? { Authorization: `Bearer ${token}` } : {} } }, []);
    const load = useCallback(async () => { setLoading(true); try { let r; try { r = await axios.get(`${API}/orders/all`, config()) } catch (first) { if (first.response?.status !== 404) throw first; r = await axios.get(`${API}/orders`, config()) } if (r.data?.statusText === "error") throw new Error(r.data?.message || "Unable to load orders"); setOrders(getArray(r, "orders")); } catch (e) { toast.error(`${errMsg(e)}. Check the admin orders GET endpoint in your backend.`) } finally { setLoading(false) } }, [config]);
    useEffect(() => { load(); const interval = setInterval(() => { load(); }, 15000); return () => clearInterval(interval); }, [load]);
    const filtered = useMemo(() => orders.filter(o => { const shipping = o.shippingAddress || {}; const name = shipping.fullName || o.user?.firstName || o.user?.name || o.customerName || ""; const code = o.trackingNumber || o.orderNumber || orderId(o); return `${code} ${name} ${o.user?.email || o.email || ""}`.toLowerCase().includes(search.toLowerCase()) && (status === "all" || String(orderStatus(o)).toLowerCase() === status.toLowerCase()) }), [orders, search, status]);
    const changeStatus = async (order, next) => { const id = orderId(order); setUpdating(id); try { await axios.patch(`${API}/orders/${id}/status`, { status: next }, config()); toast.success(`Order status changed to ${next}`); setSelected(null); await load() } catch (e) { toast.error(`${errMsg(e)}. Verify your backend status-update route.`) } finally { setUpdating("") } };
    const panel = dark ? "border-white/10 bg-slate-900/70" : "border-slate-200 bg-white", text = dark ? "text-slate-100" : "text-slate-800", muted = dark ? "text-slate-400" : "text-slate-500", field = `rounded-xl border px-3 py-2.5 text-sm outline-none focus:border-violet-500 ${dark ? "border-white/10 bg-slate-950 text-slate-100" : "border-slate-200 bg-white text-slate-800"}`;
    const pending = orders.filter(o => ["pending", "processing", "placed"].includes(String(orderStatus(o)).toLowerCase())).length; const completed = orders.filter(o => ["delivered", "completed"].includes(String(orderStatus(o)).toLowerCase())).length;
    return <section className={`min-h-[65vh] ${text}`}><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.2em] text-violet-500">Store management</p><h1 className="flex items-center gap-3 text-2xl font-bold sm:text-3xl">Orders & notifications <BellRing size={24} className="text-violet-500" /></h1><p className={`mt-1 text-sm ${muted}`}>Monitor customer orders and update their fulfilment status.</p></div><button onClick={load} className={`flex items-center justify-center gap-2 rounded-xl border px-3 py-2.5 text-sm ${panel}`}><RefreshCw size={15} /> Refresh orders</button></div>
        <div className="mb-5 grid gap-4 sm:grid-cols-3"><div className={`rounded-2xl border p-5 ${panel}`}><ShoppingBag className="mb-3 text-violet-500" /><p className={`text-sm ${muted}`}>Total orders</p><p className="mt-1 text-2xl font-bold">{orders.length}</p></div><div className={`rounded-2xl border p-5 ${panel}`}><Clock3 className="mb-3 text-amber-500" /><p className={`text-sm ${muted}`}>Pending / processing</p><p className="mt-1 text-2xl font-bold">{pending}</p></div><div className={`rounded-2xl border p-5 ${panel}`}><CheckCircle2 className="mb-3 text-emerald-500" /><p className={`text-sm ${muted}`}>Completed</p><p className="mt-1 text-2xl font-bold">{completed}</p></div></div>
        <div className={`overflow-hidden rounded-2xl border ${panel}`}><div className="flex flex-col gap-3 border-b border-inherit p-4 sm:flex-row"><div className="relative flex-1"><Search size={16} className={`absolute left-3 top-1/2 -translate-y-1/2 ${muted}`} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search order, customer, tracking number…" className={`${field} w-full pl-9`} /></div><select value={status} onChange={e => setStatus(e.target.value)} className={field}><option value="all">All statuses</option>{["Pending", "Processing", "Shipped", "Delivered", "Cancelled"].map(s => <option key={s} value={s}>{s}</option>)}</select></div>
            {loading ? <div className={`p-12 text-center ${muted}`}>Loading orders…</div> : filtered.length === 0 ? <div className={`p-12 text-center ${muted}`}><BellRing size={28} className="mx-auto mb-3 opacity-50" /><p className="font-semibold">No orders found</p><p className="mt-1 text-xs">New customer orders will appear here once the backend endpoint returns them.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className={dark ? "bg-white/[.04] text-slate-400" : "bg-slate-50 text-slate-500"}><tr>{["Order", "Customer", "Date", "Total", "Status", "Action"].map(x => <th key={x} className="px-5 py-4 text-xs font-semibold uppercase tracking-wide">{x}</th>)}</tr></thead><tbody>{filtered.map(o => { const ship = o.shippingAddress || {}; const customer = ship.fullName || [o.user?.firstName, o.user?.lastName].filter(Boolean).join(" ") || o.user?.name || o.customerName || o.email || "Customer"; const st = orderStatus(o); const date = o.createdAt ? new Date(o.createdAt).toLocaleDateString() : "—"; return <tr key={orderId(o)} className="border-t border-inherit"><td className="px-5 py-4"><p className="font-semibold">#{String(o.orderNumber || o.trackingNumber || orderId(o)).slice(-14)}</p><p className={`mt-1 text-xs ${muted}`}>{o.trackingNumber || "No tracking number"}</p></td><td className="px-5 py-4"><p className="font-medium">{customer}</p><p className={`mt-1 text-xs ${muted}`}>{o.user?.email || o.email || "—"}</p></td><td className={`px-5 py-4 ${muted}`}>{date}</td><td className="px-5 py-4 font-semibold">{money(o.total ?? o.totalAmount ?? o.amount)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${["delivered", "completed"].includes(String(st).toLowerCase()) ? "bg-emerald-500/10 text-emerald-500" : ["cancelled", "canceled"].includes(String(st).toLowerCase()) ? "bg-rose-500/10 text-rose-500" : "bg-amber-500/10 text-amber-500"}`}>{st}</span></td><td className="px-5 py-4"><button onClick={() => setSelected(o)} className="inline-flex items-center gap-2 rounded-lg border border-inherit px-3 py-2 text-xs font-semibold hover:text-violet-500"><Eye size={14} /> Details</button></td></tr> })}</tbody></table></div>}</div>
        {selected && <div className="fixed inset-0 z-[100] flex items-center justify-center overflow-y-auto bg-black/60 p-4"><div className={`my-6 w-full max-w-xl rounded-2xl border p-6 shadow-2xl ${panel}`}><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-bold">Order details</h2><p className={`mt-1 text-xs ${muted}`}>#{orderId(selected)}</p></div><button onClick={() => setSelected(null)}><X size={18} /></button></div><div className="grid gap-3 sm:grid-cols-2">{[["Customer", selected.shippingAddress?.fullName || selected.user?.name || selected.customerName || "Customer"], ["Email", selected.user?.email || selected.email || "—"], ["Phone", selected.shippingAddress?.phone || selected.phone || "—"], ["Date", selected.createdAt ? new Date(selected.createdAt).toLocaleString() : "—"], ["Payment", selected.paymentMethod || "—"], ["Total", money(selected.total ?? selected.totalAmount ?? selected.amount)], ["Tracking", selected.trackingNumber || "Not assigned"], ["Current status", orderStatus(selected)]].map(([k, v]) => <div key={k} className={`rounded-xl border border-inherit p-3`}><p className={`text-xs ${muted}`}>{k}</p><p className="mt-1 break-words text-sm font-semibold">{String(v)}</p></div>)}</div><div className="mt-5"><p className="mb-2 text-sm font-semibold">Update order status</p><div className="flex flex-wrap gap-2">{["Pending", "Processing", "Shipped", "Delivered", "Cancelled"].map(s => <button key={s} disabled={updating === orderId(selected) || String(orderStatus(selected)).toLowerCase() === s.toLowerCase()} onClick={() => changeStatus(selected, s)} className={`rounded-xl border border-inherit px-3 py-2 text-xs font-semibold hover:border-violet-500 hover:text-violet-500 disabled:opacity-40`}>{updating === orderId(selected) ? "Saving…" : s}</button>)}</div><p className={`mt-3 text-xs ${muted}`}>Status changes require PATCH /api/orders/:id/status in the backend.</p></div></div></div>}
    </section>;
}; export default AdminOrderNotification;
